### ISSUE TITLE
unable to pub add place_picker ^0.10.0

### ISSUE THREAD

**Issue by induwarar** [blackmann/locationpicker#88]
Because place_picker >=0.10.0 depends on http ^0.13.5 and project depends on http ^1.1.0, place_picker >=0.10.0 is forbidden.
So, because project depends on place_picker ^0.10.0, version solving failed.

**Comment by lyabs243** [comment]
The package has not been updated since long, To solve this you can add the package in your pubspec like this:

```
place_picker:
    git:
      url: https://github.com/lyabs243/locationpicker.git
      ref: 0.10.0
```
